In [14]:
import numpy as np
arr = np.array([[1, 3, 4], [5, 1, 0], [6, 4, 3]])


data = np.delete(arr, [0, 1], 0)
print(arr, data, sep="\n\n")

[[1 3 4]
 [5 1 0]
 [6 4 3]]

[[6 4 3]]


In [38]:
arr = np.array([[1, 3, 4], [5, 1, 0], [6, 4, 3]])
a = [[0], [8], [2]]
np.insert(arr, [2], a, axis=1)

array([[1, 3, 0, 4],
       [5, 1, 8, 0],
       [6, 4, 2, 3]])

In [35]:
np.insert(a, [1], [[7],[8],[9]], axis=1)
# np.insert(a, 1, [[7],[8],[9]], axis=1)


array([[0, 7],
       [8, 8],
       [2, 9]])